spring:
  application:
    name: ws-yoke-event

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres

encrypt:
  key: _LT_54MX2e<T)ovEZRa7J##VlEMG}Y

yoke:
  notify:
    url: http://localhost:8085/event

server:
  port: 8083
    
