spring:
  application:
    name: ws-yoke-event

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://yoke-event-postgres:5435/postgres
    username: postgres
    password: postgres
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://eureka:8761/eureka/

yoke:
  notify:
     url: http://ws-yoke-notify/event
    #url: http://localhost:8085/event

server:
  port: 8083
    
