spring:
  application:
    name: ws-yoke-event

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: '{cipher}12ee9da17bd0dfd035b0254accabe1786883d3595808986b582cbe45db456642'

yoke:
  notify:
    url: http://localhost:8085/event

server:
  port: 8083
    
